// Copyright 2017-2025 @pezkuwi/wasm-crypto-init authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Do not edit, auto-generated by @polkadot/dev
// (packageInfo imports will be kept as-is, user-editable)

import { detectPackage } from '@pezkuwi/util';
import { packageInfo as bridgeInfo } from '@pezkuwi/wasm-bridge/packageInfo';
import { packageInfo as asmInfo } from '@pezkuwi/wasm-crypto-asmjs/packageInfo';
import { packageInfo as wasmInfo } from '@pezkuwi/wasm-crypto-wasm/packageInfo';

import { packageInfo } from './packageInfo.js';

detectPackage(packageInfo, null, [asmInfo, bridgeInfo, wasmInfo]);
